version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies]
    open-pull-requests-limit: 5

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies]
    open-pull-requests-limit: 5
